n1 = [("赤字", "あかじ", "deficit"),
("悪事", "あくじ", "evil deed, crime"),
("圧倒", "あっとう", "overwhelm, overpower"),
("扱い", "あつかい", "treatment, service​"),
("圧力", "あつりょく", "pressure, stress​"),
("過ち", "あやまち", "fault, error, indiscretion"),
("買収", "ばいしゅう", "acquisition, buy-out, takeover"),
("爆弾", "ばくだん", "bomb"),
("弁護", "べんご", "defence, pleading, advocacy​"),
("弁解", "べんかい", "justification, explanation"),
("弁明", "べんめい", "explanation, excuse"),
("貧乏", "びんぼう", "poverty, destitute, poor​"),
("敏感", "びんかん", "sensibility, susceptibility"),
("微笑", "びしょう", "smile"),
("膨張", "ぼうちょう", "expansion, swelling, increase"),
("防衛", "ぼうえい", "defense, protection"),
("暴力", "ぼうりょく", "violence, mayhem"),
("侮辱", "ぶじょく", "insult, affront, slight"),
("部下", "ぶか", "subordinate person"),
("分配", "ぶんぱい", "division, splitting, sharing"),
("分散", "ぶんさん", "dispersion, breakup"),
("文書", "ぶんしょ", "document, writing, paperwork"),
("無礼", "ぶれい", "impolite, rude​"),
("武装", "ぶそう", "arms, armament​"),
("着手", "ちゃくしゅ", "to start work (on), to undertake​"),
("近づく", "ちかづく", "to approach, to draw near"),
("蓄積", "ちくせき", "accumulation, accumulate"),
("賃金", "ちんぎん", "wages"),
("沈黙", "ちんもく", "silence, being silent"),
("知性", "ちせい", "intelligence"),
("秩序", "ちつじょ", "order, regularity"),
("直感", "ちょっかん", "intuition, instinct, hunch"),
("直面", "ちょくめん", "confrontation, to face"),
("挑戦", "ちょうせん", "challenge, defiance, dare"),
("調達", "ちょうたつ", "supply, provision"),
("中断", "ちゅうだん", "interruption, suspension, break​"),
("忠実", "ちゅうじつ", "faithfulness, devotion, loyalty"),
("忠告", "ちゅうこく", "advice, warning​"),
("打撃", "だげき", "blow, shock, strike"),
("大胆", "だいたん", "bold, daring, audacious​"),
("妥協", "だきょう", "compromise, giving in​"),
("団結", "だんけつ", "unity, union, combination"),
("脱出", "だっしゅつ", "escape, break-out​"),
("土台", "どだい", "foundation, base, basis​"),
("独裁", "どくさい", "dictatorship, despotism​"),
("独占", "どくせん", "monopoly, monopolization​"),
("度胸", "どきょう", "courage, bravery, nerve"),
("動員", "どういん", "mobilization"),
("同情", "どうじょう", "sympathy, compassion"),
("動機", "どうき", "motive, incentive​"),
("同盟", "どうめい", "alliance, union, league"),
("同類", "どうるい", "the same kind"),
("同士", "どうし", "fellow, companion, comrade"),
("同等", "どうとう", "equality, equal, same rights"),
("動揺", "どうよう", "shaking, trembling, disturbance"),
("映像", "えいぞう", "reflection, image, video"),
("演じる", "えんじる", "to perform (a play), to play (a part)"),
("不動産", "ふどうさん", "real estate​"),
("腐敗", "ふはい", "decomposition, corruption, decay"),
("不可欠", "ふかけつ", "indispensable, essential​"),
("復讐", "ふくしゅう", "revenge"),
("紛争", "ふんそう", "dispute, trouble, strife​"),
("相応しい", "ふさわしい", "appropriate, adequate"),
("負傷", "ふしょう", "injury, wound​"),
("負担", "ふたん", "burden, charge, responsibility​"),
("不当", "ふとう", "injustice, impropriety, unfair"),
("封鎖", "ふうさ", "blockade"),
("概念", "がいねん", "general idea, concept"),
("現地", "げんち", "actual place, local"),
("厳密", "げんみつ", "strict, close, precise"),
("減少", "げんしょう", "decrease, reduction, decline"),
("原則", "げんそく", "principle, general rule​"),
("幻想", "げんそう", "illusions"),
("犠牲", "ぎせい", "victim, sacrifice, scapegoat"),
("合成", "ごうせい", "composition, synthesis"),
("軍事", "ぐんじ", "military affairs​"),
("業務", "ぎょうむ", "business, affairs, duties"),
("業績", "ぎょうせき", "achievement, performance, results"),
("把握", "はあく", "grasp, catch, understanding​"),
("阻む", "はばむ", "to keep someone from doing, to prevent"),
("肺", "はい", "lung"),
("配置", "はいち", "arrangement, deployment"),
("背後", "はいご", "back, rear, ​background"),
("排除", "はいじょ", "exclusion, removal, elimination"),
("配慮", "はいりょ", "consideration, concern, attention"),
("廃止", "はいし", "abolition, repeal​"),
("破壊", "はかい", "destruction, disruption​"),
("派遣", "はけん", "dispatch, despatch, deployment​"),
("白状", "はくじょう", "confession"),
("繁栄", "はんえい", "prosperity, thriving"),
("反応", "はんのう", "reaction, response​"),
("反乱", "はんらん", "insurrection, rebellion"),
("発生", "はっせい", "outbreak, spring forth, occurrence"),
("果たす", "はたす", "to accomplish, to achieve"),
("発言", "はつげん", "statement, remark"),
("兵器", "へいき", "arms, weapons, ordnance​"),
("閉鎖", "へいさ", "closing, shutdown, lockout"),
("兵士", "へいし", "soldier"),
("変動", "へんどう", "change, fluctuation​"),
("変革", "へんかく", "change, transformation"),
("偏見", "へんけん", "prejudice, narrow view​"),
("率いる", "ひきいる", "to lead, to command"),
("悲鳴", "ひめい", "shriek, scream​"),
("非難", "ひなん", "criticism, blame, reproach"),
("避難", "ひなん", "taking refuge, finding shelter"),
("貧困", "ひんこん", "poor, needy​"),
("頻繁", "ひんぱん", "frequent, incessant"),
("疲労", "ひろう", "fatigue, weariness​"),
("悲惨", "ひさん", "disastrous, tragic"),
("匹敵", "ひってき", "to be a match for, to rival"),
("必然", "ひつぜん", "inevitable, necessary"),
("施す", "ほどこす", "to give, to do, to conduct"),
("保護", "ほご", "care, protection, shelter"),
("保険", "ほけん", "insurance, guarantee​"),
("本能", "ほんのう", "instinct"),
("本心", "ほんしん", "true feelings​"),
("本質", "ほんしつ", "essence, true nature"),
("崩壊", "ほうかい", "collapse, crumbling"),
("放棄", "ほうき", "abandonment, renunciation"),
("方策", "ほうさく", "plan, policy​"),
("報酬", "ほうしゅう", "remuneration, recompense, reward")]
