n2 = [("明け方", "あけがた", "dawn"),
("青白い", "あおじろい", "pale; bluish-white"),
("足跡", "あしあと", "footprints"),
("売買", "ばいばい", "trade; buying and selling"),
("売店", "ばいてん", "stand; stall; booth; kiosk; store"),
("募集", "ぼしゅう", "recruitment; invitation; taking applications; solicitation"),
("長男", "ちょうなん", "eldest son; first-born son"),
("楕円", "だえん", "ellipse"),
("大学院", "だいがくいん", "graduate school"),
("出入口", "でいりぐち", "exit and entrance"),
("宴会", "えんかい", "party; banquet; reception; feast; dinner"),
("円周", "えんしゅう", "circumference"),
("遠足", "えんそく", "excursion; outing; trip"),
("父母", "ふぼ", "father and mother; parents"),
("学科", "がっか", "study subject; course of study​; department"),
("学会", "がっかい", "scientific society; academic meeting; academic conference"),
("学力", "がくりょく", "scholarly ability; scholarship; knowledge; literary ability"),
("外科", "げか", "surgery; department of surgery"),
("花火", "はなび", "fireworks"),
("半径", "はんけい", "radius"),
("半島", "はんとう", "peninsula"),
("発売", "はつばい", "sale; release (for sale); launch (product)"),
("早口", "はやぐち", "fast-talking; rapid talking"),
("外れる", "はずれる", "to be disconnected; to be off; to miss the mark"),
("閉会", "へいかい", "closure (of a ceremony, event, meeting, etc.)"),
("昼寝", "ひるね", "nap, siesta"),
("意地悪", "いじわる", "malicious; ill-tempered; unkind"),
("移転", "いてん", "moving; relocation; change of address"),
("一旦", "いったん", "once; for a short time; briefly; temporarily"),
("寺院", "じいん", "Buddhist temple; religious building"),
("人文科学", "じんぶんかがく", "humanities; social sciences; liberal arts"),
("自習", "じしゅう", "self-study; teaching oneself"),
("時速", "じそく", "speed (per hour)"),
("実習", "じっしゅう", "practice; training; practical exercise; drill"),
("過半数", "かはんすう", "majority"),
("開会", "かいかい", "opening of a meeting; starting (an event, etc.)"),
("会館", "かいかん", "meeting hall; assembly hall"),
("回転", "かいてん", "rotation; revolution; turning"),
("加速", "かそく", "acceleration; speeding up"),
("加速度", "かそくど", "acceleration"),
("見学", "けんがく", "study by observation; field trip; tour; review; inspection"),
("国王", "こくおう", "king; queen; monarch; sovereign"),
("国立", "こくりつ", "national"),
("国籍", "こくせき", "nationality; citizenship"),
("転がる", "ころがる", "to roll; to fall over; to lie down"),
("転がす", "ころがす", "to roll; to turn over"),
("校舎", "こうしゃ", "school building; schoolhouse"),
("校庭", "こうてい", "schoolyard; playground; school grounds; campus"),
("待合室", "まちあいしつ", "waiting room"),
("待ち合わせる", "まちあわせる", "to rendezvous; to meet at a prearranged place and time; to arrange to meet"),
("窓口", "まどぐち", "ticket window; teller window; counter"),
("毎度", "まいど", "each time; always; often; thank you for your continued patronage​"),
("真っ青", "まっさお", "deep blue; bright blue​; ghastly pale; white as a sheet"),
("真っ白", "まっしろ", "pure white; blank"),
("名刺", "めいし", "business card"),
("店屋", "みせや", "store; shop"),
("木材", "もくざい", "lumber; timber; wood"),
("元々", "もともと", "originally, by nature, from the start"),
("内科", "ないか", "internal medicine"),
("並木", "なみき", "roadside tree; row of trees"),
("入社", "にゅうしゃ", "joining a company"),
("押さえる", "おさえる", "to pin down; to hold down; to press down"),
("理科", "りか", "science (department; course)"),
("領収", "りょうしゅう", "receipt (of money); receiving"),
("再三", "さいさん", "again and again; repeatedly"),
("刺さる", "ささる", "to stick into (with a sharp point); to prick; to get stuck (in)"),
("刺身", "さしみ", "sashimi (raw sliced fish, shellfish, or crustaceans)"),
("早速", "さっそく", "at once; immediately; without delay; promptly"),
("刺す", "さす", "to pierce; to stab; to prick; to stick; to thrust; to sting"),
("青少年", "せいしょうねん", "youth; young person"),
("赤道", "せきどう", "equator"),
("社会科学", "しゃかいかがく", "social science"),
("社説", "しゃせつ", "editorial; leading article; leader"),
("司会", "しかい", "master of ceremonies; leading a meeting; presenter; host"),
("新幹線", "しんかんせん", "Japanese bullet train"),
("白髪", "しらが", "white hair; grey hair"),
("自然科学", "しぜんかがく", "natural science"),
("書店", "しょてん", "bookshop; bookstore"),
("商社", "しょうしゃ", "trading company; firm"),
("商店", "しょうてん", "shop; small store; business; firm"),
("集合", "しゅうごう", "gathering; assembly; meeting"),
("習字", "しゅうじ", "calligraphy; penmanship"),
("集会", "しゅうかい", "meeting; assembly; gathering; convention; rally"),
("速力", "そくりょく", "speed"),
("速達", "そくたつ", "express; special delivery"),
("足袋", "たび", "Japanese socks (with split toe)"),
("足る", "たる", "to be sufficient; to be enough​; to be worth doing; to be worthy of; to deserve​"),
("特売", "とくばい", "special sale"),
("透明", "とうめい", "transparent; clear"),
("東洋", "とうよう", "Orient"),
("売れ行き", "うれゆき", "sales; demand"),
("売上", "うりあげ", "amount sold; sales; proceeds; turnover"),
("売り切れ", "うりきれ", "sold out"),
("売り切れる", "うりきれる", "to be sold out"),
("我が", "わが", "my; our; one's own"),
("洋品店", "ようひんてん", "shop that handles Western-style apparel and accessories"),
("輸血", "ゆけつ", "blood transfusion"),
("輸送", "ゆそう", "transport; transportation"),
("材木", "ざいもく", "lumber; timber"),
]
