n3 = [('1', 'one', 'this is the definition of one'),
                    ('2', 'two', 'this is the definition of two')]
    # ("明かり", "あかり", "light; illumination; glow; gleam"),
    # ("明ける", "あける", "to dawn; to become daylight"),
    # ("明らか", "あきらか", "clear; obvious"),
    # ("悪魔", "あくま", "devil; demon; fiend; Satan"),
    # ("暗記", "あんき", "memorization; learning by heart"),
    # ("新た", "あらた", "new; fresh; novel"),
    # ("有らゆる", "あらゆる", "all; every"),
    # ("集まり", "あつまり", "gathering; meeting; assembly; collection; attendance"),
    # ("部分", "ぶぶん", "portion; section; part"),
    # ("分", "ぶん", "part; segment; share; ration"),
    # ("文明", "ぶんめい", "civilization; culture"),
    # ("分析", "ぶんせき", "analysis"),
    # ("分野", "ぶんや", "field; sphere; realm; division; branch"),
    # ("父親", "ちちおや", "father"),
    # ("地平線", "ちへいせん", "horizon (related to land)"),
    # ("地位", "ちい", "(social) position; status"),
    # ("長期", "ちょうき", "long-term"),
    # ("中", "ちゅう", "during; while; medium; middle"),
    # ("中学", "ちゅうがく", "junior high school; middle school"),
    # ("昼食", "ちゅうしょく", "lunch; midday meal"),
    # ("大部分", "だいぶぶん", "most part; greater part; majority"),
    # ("駄目", "だめ", "no good; cannot"),
    # ("男子", "だんし", "youth; young man"),
    # ("出会い", "であい", "meeting; rendezvous; encounter"),
    # ("出会う", "であう", "to meet (by chance); to come across; to run across; to encounter"),
    # ("読書", "どくしょ", "reading"),
    # ("努力", "どりょく", "effort; exertion; endeavor; hard work; striving"),
    # ("同一", "どういつ", "identical; same; one and the same; equal"),
    # ("円", "えん", "yen; Japanese monetary unit; circle"),
    # ("不利", "ふり", "disadvantage; handicap; unfavorable position"),
#     ("不足", "ふそく", "insufficiency; shortage; deficiency; lack; dearth"),
#     ("再び", "ふたたび", "again; once more; a second time"),
#     ("外交", "がいこう", "diplomacy"),
#     ("外出", "がいしゅつ", "going out; outing; leaving (one's home, office, etc.)"),
#     ("学期", "がっき", "school term; semester"),
#     ("学", "がく", "learning; education; study of"),
#     ("学問", "がくもん", "scholarship; study; learning"),
#     ("学者", "がくしゃ", "scholar"),
#     ("学習", "がくしゅう", "study; learning; tutorial"),
#     ("議長", "ぎちょう", "chairman; president; moderator"),
#     ("議会", "ぎかい", "congress; parliament; diet; legislative assembly"),
#     ("語学", "ごがく", "study of foreign languages; linguistics"),
#     ("激しい", "はげしい", "violent; extreme; intense"),
#     ("母親", "ははおや", "mother"),
#     ("博物館", "はくぶつかん", "museum"),
#     ("販売", "はんばい", "sales; selling; marketing"),
#     ("発明", "はつめい", "invention"),
#     ("外す", "はずす", "to remove; to undo; to drop; to miss"),
#     ("品", "ひん", "elegance; article"),
#     ("一言", "ひとこと", "single word; a few words; brief comment"),
#     ("一人一人", "ひとりひとり", "one by one; each; one at a time"),
#     ("本物", "ほんもの", "genuine article; real thing; real deal"),
#     ("本人", "ほんにん", "the person in question; the person themselves; said person"),
#     ("一致", "いっち", "agreement; union; match; coincidence"),
#     ("一時", "いちじ", "one o'clock"),
#     ("意外", "いがい", "unexpected; surprising"),
#     ("一家", "いっか", "a family; a household; a home; one's family; whole family"),
#     ("今に", "いまに", "before long; even now"),
#     ("今にも", "いまにも", "at any moment; at any minute; on the verge of"),
#     ("一般", "いっぱん", "general; universal; ordinary; average; common"),
#     ("一方", "いっぽう", "one (esp. of two); one way; the other direction; although"),
#     ("一生", "いっしょう", "whole life; a lifetime; a generation"),
#     ("一種", "いっしゅ", "species; kind; variety"),
#     ("一瞬", "いっしゅん", "instant; moment; for an instant"),
#     ("一層", "いっそう", "much more; still more; all the more; single layer; sooner; preferably"),
#     ("一体", "いったい", "(what) the heck; (why) in the world"),
#     ("所謂", "いわゆる", "what is called; as it is called; the so-called; so to speak"),
#     ("邪魔", "じゃま", "hindrance"),
#     ("化学", "かがく", "chemistry"),
#     ("会", "かい", "meeting; assembly; party; association; club"),
#     ("会員", "かいいん", "member"),
#     ("海外", "かいがい", "foreign; abroad; overseas"),
#     ("会合", "かいごう", "meeting; assembly; gathering; association"),
#     ("会計", "かいけい", "finance; account; treasurer; bill"),
#     ("開始", "かいし", "start; commencement; beginning; initiation"),
#     ("科目", "かもく", "(school) subject; curriculum; course"),
#     ("権利", "けんり", "right; privilege"),
#     ("基本", "きほん", "basics; fundamentals; basis; foundation"),
#     ("記事", "きじ", "article; news story; report; account"),
#     ("気味", "きみ", "sensation; feeling; tendency"),
#     ("記念", "きねん", "commemoration; celebration; honoring the memory of something"),
#     ("気に入る", "きにいる", "to like; to take a liking to"),
#     ("記入", "きにゅう", "entry; filling in; filling out"),
#     ("記憶", "きおく", "memory; recollection; remembrance"),
#     ("記者", "きしゃ", "reporter; journalist"),
#     ("期待", "きたい", "expectation; anticipation; hope"),
#     ("国家", "こっか", "state; country; nation"),
#     ("国会", "こっかい", "National Diet; legislative assembly of Japan; parliament; congress"),
#     ("国境", "こっきょう", "national border"),
#     ("国語", "こくご", "national language"),
#     ("国民", "こくみん", "people (of a country); nation; citizen; national"),
#     ("今後", "こんご", "from now on; hereafter"),
#     ("今回", "こんかい", "now; this time; lately"),
#     ("今日", "こんにち", "today; this day"),
#     ("転ぶ", "ころぶ", "to fall down; to fall over"),
#     ("高速", "こうそく", "high-speed; rapid; express"),
#     ("訓練", "くんれん", "training; drill; practice; discipline"),
#     ("教科書", "きょうかしょ", "textbook; coursebook; schoolbook"),
#     ("協力", "きょうりょく", "cooperation; collaboration"),
    # ("強力", "きょうりょく", "powerful; strong")

