n4 = [("あ", "a", "Ah; oh"),
("ああ", "aa", "ah; yes"),
("アフリカ", "afurika", "Africa"),
("上がる", "あがる", "to rise"),
("挨拶", "あいさつ", "to greet"),
("味", "あじ", "flavor; taste​; uniqueness; attractiveness; experience"),
("アジア", "ajia", "Asia"),
("赤ちゃん", "あかちゃん", "baby; infant"),
("赤ん坊", "あかんぼう", "baby; infant"),
("アクセサリー", "akusesarii", "accessory"),
("アメリカ", "amerika", "America"),
("アナウンサー", "anaunsaa", "announcer"),
("あんな", "anna", "such"),
("案内", "あんない", "to guide"),
("安心", "あんしん", "peace of mind"),
("安全", "あんぜん", "safety; security​"),
("アルバイト", "arubaito", "part-time job"),
("アルコール", "arukooru", "alcohol"),
("浅い", "あさい", "shallow"),
("遊び", "あそび", "playing"),
("集まる", "あつまる", "to gather; to collect; to assemble"),
("集める", "あつめる", "to collect; to assemble; to gather"),
("謝る", "あやまる", "to apologize"),
("倍", "ばい", "double"),
("番組", "ばんぐみ", "program (e.g. TV)"),
("場所", "ばしょ", "place"),
("ベル", "beru", "bell"),
("美術館", "びじゅつかん", "art gallery; art museum"),
("びっくり", "bikkuri", "to be surprised"),
("ビル", "biru", "building"),
("僕", "ぼく", "I (used by males)"),
("貿易", "ぼうえき", "trade"),
("部長", "ぶちょう", "manager; head (chief, director) of a section or department"),
("ぶどう", "ぶどう", "grapes"),
("文学", "ぶんがく", "literature"),
("文化", "ぶんか", "culture"),
("文法", "ぶんぽう", "grammar"),
("ちゃん", "chan", "suffix for familiar female person"),
("チェック", "chekku", "to check"),
("血", "ち", "blood"),
("力", "ちから", "energy; force; strength; might; power"),
("地理", "ちり", "geography"),
("中学校", "ちゅうがっこう", "junior high school; middle school"),
("注意", "ちゅうい", "caution"),
("注射", "ちゅうしゃ", "injection"),
("駐車場", "ちゅうしゃじょう", "parking lot"),
("大分", "だいぶ", "considerably; greatly; a lot​"),
("大学生", "だいがくせい", "university student; college student"),
("大事", "だいじ", "important; serious; crucial"),
("大体", "だいたい", "roughly"),
("暖房", "だんぼう", "heating"),
("男性", "だんせい", "man; male"),
("できるだけ", "dekiru dake", "as much as possible"),
("電報", "でんぽう", "telegram"),
("電灯", "でんとう", "electric light"),
("どんどん", "dondon", "rapidly; more and more"),
("泥棒", "どろぼう", "thief"),
("動物園", "どうぶつえん", "zoo; zoological gardens"),
("道具", "どうぐ", "tool"),
("枝", "えだ", "branch"),
("遠慮", "えんりょ", "reserve; refraining"),
("選ぶ", "えらぶ", "to choose"),
("エスカレーター", "esukareetaa", "escalator"),
("ファックス", "fakkusu", "fax"),
("不便", "ふべん", "inconvenience"),
("増える", "ふえる", "to increase"),
("深い", "ふかい", "deep"),
("復習", "ふくしゅう", "review (of learned material); revision"),
("複雑", "ふくざつ", "complexity; complication"),
("踏む", "ふむ", "to step on"),
("船", "ふね", "ship"),
("降り出す", "ふりだす", "to start to rain"),
("布団", "ふとん", "Japanese bedding, futon"),
("太る", "ふとる", "to become fat"),
("普通", "ふつう", "usually"),
("ガラス", "garasu", "a glass"),
("ガソリン", "gasorin", "gasoline; petrol"),
("ガソリンスタンド", "gasorin sutando", "petrol station"),
("ガス", "gasu", "petrol"),
("原因", "げんいん", "cause"),
("下宿", "げしゅく", "lodging"),
("技術", "ぎじゅつ", "art,technology,skill"),
("ごちそう", "ごちそう", "a feast"),
("ごみ", "ごみ", "rubbish"),
("ご覧になる", "ごらんになる", "(respectful) to see"),
("ご主人", "ごしゅじん", "your husband; her husband"),
("ご存じ", "ごぞんじ", "knowing"),
("具合", "ぐあい", "condition; health"),
("葉", "は", "leaves; leaf"),
("拝見", "はいけん", "seeing; looking at​"),
("歯医者", "はいしゃ", "dentist"),
("はっきり", "はっきり", "clearly"),
("運ぶ", "はこぶ", "to carry"),
("花見", "はなみ", "cherry blossom viewing; flower viewing"),
("ハンドバッグ", "handobaggu", "handbag"),
("反対", "はんたい", "opposition"),
("払う", "はらう", "to pay"),
("発音", "はつおん", "pronunciation"),
("林", "はやし", "woods; forest"),
("恥ずかしい", "はずかしい", "embarrassed")
]
