n5 = [("浴びる", "あびる", "to bathe, to shower"),
   ("危ない", "あぶない", "dangerous"),
   ("あっち", "acchi", "over there"),
   ("あちら", "achira", "there"),
   ("上げる", "あげる", "to raise; to elevate; to give"),
   ("赤", "あか", "red; crimson; scarlet"),
   ("赤い", "あかい", "red; crimson; scarlet"),
   ("明るい", "あかるい", "bright; light"),
   ("開ける", "あける", "to open (a door, etc.); to unwrap (e.g. parcel, package); to unlock"),
   ("秋", "あき", "autumn; fall"),
   ("開く", "あく", "to open (e.g. doors, business, etc)"),
   ("甘い", "あまい", "sweet; sweet-tasting; sugary; naive; indulgent"),
   ("雨", "あめ", "rain"),
   ("飴", "あめ", "candy"),
   ("あなた", "anata", "you"),
   ("姉", "あね", "older sister; elder sister"),
   ("兄", "あに", "elder brother; older brother"),
   ("あの", "ano", "that"),
   ("青", "あお", "blue; azure"),
   ("青い", "あおい", "blue; azure"),
   ("アパート", "apaato", "apartment"),
   ("洗う", "あらう", "to wash"),
   ("あれ", "are", "that"),
   ("ある", "ある", "to be, to have"),
   ("歩く", "あるく", "to walk"),
   ("朝", "あさ", "morning"),
   ("朝ご飯", "あさごはん", "breakfast"),
   ("明後日", "あさって", "day after tomorrow"),
   ("足", "あし", "foot; leg; paw; arm"),
   ("明日", "あした", "tomorrow"),
   ("遊ぶ", "あそぶ", "to play; to enjoy oneself"),
   ("あそこ", "asoko", "over there"),
   ("頭", "あたま", "head"),
   ("新しい", "あたらしい", "new; novel; fresh; recent; latest"),
   ("暖かい", "あたたかい", "warm"),
   ("後", "あと", "behind; after; remainder; left; also"),
   ("暑い", "あつい", "hot; sultry"),
   ("厚い", "あつい", "thick"),
   ("熱い", "あつい", "hot"),
   ("会う", "あう", "to meet; to encounter; to see"),
   ("晩ご飯", "ばんごはん", "dinner; evening meal"),
   ("番号", "ばんごう", "number"),
   ("バス", "basu", "bus"),
   ("バター", "bataa", "butter"),
   ("ベッド", "beddo", "bed"),
   ("勉強", "べんきょう", "to study"),
   ("便利", "べんり", "convenient; handy; useful"),
   ("ボールペン", "boorupen", "ball-point pen"),
   ("ボタン", "botan", "button"),
   ("帽子", "ぼうし", "hat; cap"),
   ("文章", "ぶんしょう", "sentence"),
   ("豚肉", "ぶたにく", "pork"),
   ("病院", "びょういん", "hospital"),
   ("病気", "びょうき", "illness; disease; sickness"),
   ("茶色", "ちゃいろ", "brown"),
   ("茶碗", "ちゃわん", "rice bowl; tea cup; teacup"),
   ("父", "ちち", "father"),
   ("違う", "ちがう", "to differ"),
   ("小さい", "ちいさい", "small; little; tiny"),
   ("小さな", "ちいさな", "small; little; tiny"),
   ("近い", "ちかい", "near; close"),
   ("地下鉄", "ちかてつ", "subway; underground train"),
   ("地図", "ちず", "map"),
   ("ちょっと", "chotto", "a little"),
   ("丁度", "ちょうど", "exactly"),
   ("台所", "だいどころ", "kitchen"),
   ("大学", "だいがく", "university; college"),
   ("大丈夫", "だいじょうぶ", "OK; okay; alright; problem free"),
   ("大好き", "だいすき", "love; like; like very much"),
   ("だんだん", "dandan", "gradually"),
   ("誰", "だれ", "who"),
   ("誰か", "だれか", "someone; somebody"),
   ("出す", "だす", "to take out; to get out; to put out; to reveal"),
   ("出口", "でぐち", "exit; gateway; way out"),
   ("出かける", "でかける", "to go out; to leave; to depart"),
   ("電気", "でんき", "electricity"),
   ("電車", "でんしゃ", "train; electric train"),
   ("電話", "でんわ", "telephone (call / device)l; phone call"),
   ("デパート", "depaato", "department store"),
   ("出る", "でる", "to leave; to exit; to appear; to go out"),
   ("ドア", "doa", "door"),
   ("どっち", "docchi", "which; which one"),
   ("どちら", "dochira", "which of two"),
   ("どこ", "doko", "where; what place"),
   ("どなた", "donata", "who"),
   ("どの", "dono", "which"),
   ("どれ", "dore", "which (of three or more)"),
   ("どう", "dou", "how; in what way; how about"),
   ("動物", "どうぶつ", "animal"),
   ("どうも", "doumo", "thank you; thanks"),
   ("どうぞ", "douzo", "please"),
   ("土曜日", "どようび", "Saturday"),
   ("絵", "え", "picture"),
   ("ええ", "ee", "yes; that is correct; right"),
   ("映画", "えいが", "movie; film"),
   ("映画館", "えいがかん", "movie theater; cinema"),
   ("英語", "えいご", "English language"),
   ("駅", "えき", "station"),
   ("鉛筆", "えんぴつ", "pencil"),
   ("エレベーター", "erebeetaa", "elevator")]
